export const BrandName = 'Zikation'
export const PhoneNumber = "+91 821 762 6812"
export const SiteBaseURL = "https://zikation.com"
export const WhatsAppNumber = "918217626812"
export const WhatsAppURL = "https://wa.me/" + WhatsAppNumber
export const Email = "zikationindia@gmail.com"
export const FaceBookURL = "https://facebook.com/zikation"
export const InstagramURL = "https://instagram.com/zikation"
export const xURL = "https://x.com/zikationindia"
export const YouTubeURL = "#"
export const DefaultImage = "/images/default-tour.jpg"
export const DefaultTourImage = "/images/default-tour.jpg"
export const LogoImage = '/logo/zikation.png'